load("@bazel_gazelle//:def.bzl", "gazelle")
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

# gazelle:prefix github.com/stripe/skycfg
# gazelle:build_file_name BUILD.bazel,BUILD
# gazelle:go_naming_convention import

# gazelle:exclude _examples

go_library(
    name = "skycfg",
    srcs = [
        "reader.go",
        "skycfg.go",
    ],
    importpath = "github.com/stripe/skycfg",
    visibility = ["//visibility:public"],
    deps = [
        "//go/assertmodule",
        "//go/hashmodule",
        "//go/protomodule",
        "//go/urlmodule",
        "//go/yamlmodule",
        "@net_starlark_go//lib/json",
        "@net_starlark_go//starlark",
        "@net_starlark_go//starlarkstruct",
        "@net_starlark_go//syntax",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//reflect/protoregistry",
    ],
)

go_test(
    name = "skycfg_test",
    size = "small",
    srcs = [
        "export_test.go",
        "skycfg_test.go",
    ],
    embed = [":skycfg"],
    deps = [
        "//internal/test_proto:test_proto_go_proto",
        "@net_starlark_go//starlark",
        "@net_starlark_go//syntax",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/wrapperspb",
    ],
)

gazelle(name = "gazelle")

gazelle(
    name = "gazelle-update-repos",
    args = [
        "-from_file=go.mod",
        "-to_macro=build/go_dependencies.bzl%go_dependencies",
        "-prune",
    ],
    command = "update-repos",
)
