name: "Tests"
on: ["push", "pull_request"]

# This disables all permissions since we don't use GITHUB_TOKEN.
permissions: {}

jobs:
  tests:
    name: "Go ${{ matrix.go.series }}"
    runs-on: "ubuntu-24.04"
    container:
      # Keep this in sync with .bazelversion
      image: "docker://gcr.io/bazel-public/bazel:8.4.2"
      options: --user root

    strategy:
      matrix:
        go:
          # Keep minimum version up to date with go.mod
          # Keep version list in sync with MODULE.bazel
          - series: "1.22"
            version: "1.22.12"
          - series: "1.23"
            version: "1.23.12"
          - series: "1.24"
            version: "1.24.9"
          - series: "1.25"
            version: "1.25.3"

    steps:
      - uses: "actions/checkout@v4"
        with:
          path: "src"
      - uses: "actions/cache@v4"
        with:
          path: cache
          key: "go=${{ matrix.go.version }};v=1"
      - name: "bazel test //..."
        working-directory: src
        run: |
          exec bazel test \
            --announce_rc \
            --curses=no \
            --color=yes \
            --verbose_failures \
            --test_output=errors \
            --test_verbose_timeout_warnings \
            --repository_cache="$GITHUB_WORKSPACE/cache/repository_cache" \
            --disk_cache="$GITHUB_WORKSPACE/cache/disk_cache" \
            --@io_bazel_rules_go//go/config:race \
            --@io_bazel_rules_go//go/toolchain:sdk_version="$GO_VERSION" \
            //...
        env:
          GO_VERSION: ${{ matrix.go.version }}
